# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM nvcr.io/nvidia/isaac-lab:2.3.2

RUN apt update && \
    apt install -y \
	build-essential \
	cmake \
	curl \
	git

RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.96.4

RUN apt update && \
	apt install -y \
	unzip \
	dnsutils \
	iproute2 \
	jq

ENV WORKSPACE_DIR=/workspace
ENV ISAACLAB=/workspace/isaaclab

COPY --chown=isaac-sim:isaac-sim ./README.md ${WORKSPACE_DIR}/README.md
COPY --chown=isaac-sim:isaac-sim ./settings.json ${WORKSPACE_DIR}/.vscode/settings.json
COPY --chown=isaac-sim:isaac-sim ./tasks.json ${WORKSPACE_DIR}/.vscode/tasks.json
COPY --chown=isaac-sim:isaac-sim ./contact_rich_manipulation/ ${WORKSPACE_DIR}/contact_rich_manipulation/
COPY --chown=isaac-sim:isaac-sim ./policy/ ${WORKSPACE_DIR}/policy/


RUN code-server \
    --install-extension ms-python.python \
    --install-extension ms-toolsai.jupyter \
    --force ${WORKSPACE_DIR}

COPY entrypoint.sh /entrypoint.sh

# OV Cache Directories
RUN mkdir -p /home/isaac-sim/.cache/ov
RUN mkdir -p /home/isaac-sim/.local/share/ov

# Fix permissions for ubuntu user
RUN chown -R isaac-sim /workspace /home/isaac-sim/.cache/ov /home/isaac-sim/.local/share/ov /isaac-sim/kit/cache

# Copy bashrc to get aliases
RUN cp /root/.bashrc /isaac-sim/.root-bashrc
RUN echo 'source $HOME/.root-bashrc' >> /isaac-sim/.bashrc

USER isaac-sim:isaac-sim

ENTRYPOINT ["/bin/bash"]

CMD ["/entrypoint.sh"]
